### PR TITLE
delete old examples directory

### PR DESCRIPTION
**Pull request by fifield**
`examples` is replaced by `programming_examples` directory (#590).  The new folder is tested in the CI and known to work which is better than the old `examples` directory. The best way I can think of to clean up `examples` is to delete it. If anyone still wants one of the old examples we can resurrect it and put it in the new area.

### CODE REVIEW

**Comment by erwei-xilinx** [comment]
I agree with removing the air-runner and air-dependency examples as they are obsolete. Might also worth checking with Gagan and Eddie on the weather stencil examples.

**Review by jgmelber — APPROVED** [review]
LGTM. We will try to capture a list of relevant `examples` we want to redevelop as `programming_examples`.

- Channels examples
- Attention head (airbert)
- matmul gelu (and more activations)
- MLP
- matmul
- conv
- weather stencil

@hunhoffe @denolf @singagan @abisca

**Comment by jgmelber** [comment]
> I agree with removing the air-runner and air-dependency examples as they are obsolete. Might also worth checking with Gagan and @eddierichter-amd on the weather stencil examples.

Agreed, I think the interesting _AIR_ parts from the weather stencil are captured here: https://github.com/Xilinx/ROCm-air-platforms/tree/main/examples/sparta-weather-stencil

**Comment by eddierichter-amd** [comment]
> > I agree with removing the air-runner and air-dependency examples as they are obsolete. Might also worth checking with Gagan and @eddierichter-amd on the weather stencil examples.
> 
> Agreed, I think the interesting _AIR_ parts from the weather stencil are captured here: https://github.com/Xilinx/ROCm-air-platforms/tree/main/examples/sparta-weather-stencil

Agreed, removing the weather stencil in this repo is fine with me.

**Pull request merged**
