### PR TITLE
enable e2e test on RyzenAI

### PR DESCRIPTION
**Pull request by fifield**
* add xrt as an e2e test platform
* add exisiting air_to_ipu example as xrt unit test
* the cmake option `ENABLE_BOARD_TESTS` is replaced with `ENABLE_RUN_AIRHOST_TESTS` (for vck5000) or `ENABLE_RUN_XRT_TESTS` (for ryzen ai)
* build target `check-air-board` replaced with `check-air-e2e`

### CODE REVIEW

**Comment by fifield** [comment]
> it was working but broke when I rebased

broken due to #389

**Comment by erwei-xilinx** [comment]
Please see if this patch fixes the issue: https://github.com/Xilinx/mlir-air/pull/394

**Comment by fifield** [comment]
> Please see if this patch fixes the issue: #394

yes, it does. Thank you!

**Review by erwei-xilinx — APPROVED** [review]
Thanks for working on this. This looks really great to me.

**Pull request merged**
