### PR TITLE
Add a reduction pipelining transform using affine.if

### PR DESCRIPTION
**Pull request by fifield**
This transformation splits a linalg on memrefs reduction into pipeline stages with partial results passed from one stage to the next. The reduction pipeline is mapped to a Nx1 or 1xN herd.

### CODE REVIEW

**Review by jamesroxbypb — COMMENTED** [review]
This looks handy.  Presumably the tile-size option can be n-dimensional and the type is inferred from the type of the tensor on the reduction dimension.  Are there ever any cases where you have more than 1 reduction dimension on a linalg op?

**Comment by fifield** [comment]
> This looks handy. Presumably the tile-size option can be n-dimensional and the type is inferred from the type of the tensor on the reduction dimension. Are there ever any cases where you have more than 1 reduction dimension on a linalg op?

In the current form it only tiles along the inner dimension, which must be a reduction dimension, and tile-size applies to that dimension. There are linalg ops such as convolutions with more than one reduction dimension.

**Comment by jamesroxbypb** [comment]
Does the depth of 2 include the special last stage to do just summation?

**Comment by fifield** [comment]
> Does the depth of 2 include the special last stage to do just summation?

No, this does an even split of the linalg op across the pipeline stages. A special stage at the end is not emitted.

**Pull request merged**
