### PR TITLE
non-const static variable -> class member for a thread safe pass

### PR DESCRIPTION
**Pull request by newling**
This PR ensures (for my build setup) that compile pipeline 2 with multithreading does not segfault (I ran ~10 times)

### CODE REVIEW

**Review by nirvedhmeshram — COMMENTED** [review]
I think the problem is that this pass is changing state outside its own module, so I am curious what that state is and if we can make it not do that, we would ideally want to allow multiple threads to use the pass together if we can fix the root issue.

**Comment by newling** [comment]
> I think the problem is that this pass is changing state outside its own module, so I am curious what that state is and if we can make it not do that, we would ideally want to allow multiple threads to use the pass together if we can fix the root issue.

I think the problem is that the pass has (C++) state, which gets read/written by 2 threads.

**Comment by nirvedhmeshram** [comment]
> > I think the problem is that this pass is changing state outside its own module, so I am curious what that state is and if we can make it not do that, we would ideally want to allow multiple threads to use the pass together if we can fix the root issue.
> 
> I think the problem is that the pass class has (C++) state, which gets read/written by 2 threads.

I think C++ state is fairly standard in passes? Just giving a random example from IREE (choose a module pass as well)
https://github.com/openxla/iree/blob/main/compiler/src/iree/compiler/Codegen/LLVMCPU/ConvertToLLVM.cpp

**Comment by newling** [comment]
From  https://mlir.llvm.org/docs/PassManagement : passes "Must not maintain mutable pass state across invocations of runOnOperation". A single pass object runs on multiple operations at the same time, makes sense that of the class has mutable state then bad things might happen.

**Review by nirvedhmeshram — APPROVED** [review]
Thanks, LGTM!

**Review by erwei-xilinx — APPROVED** [review]
Thanks for working on this, LGTM!

**Pull request merged**
